server:
  port: 8080
spring:
  application: 
    name: Banking Lending Portal
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect      
    hibernate:
      ddl-auto: update   

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
          
             
            
            

